import type { TeFormRules, Verb } from "./types"

export const teFormRules: TeFormRules = {
  ichidan: {
    pattern: "る",
    replacement: "て",
    description: "For ichidan verbs, simply replace る with て",
  },
  irregular: {
    する: {
      pattern: "する",
      replacement: "して",
      description: "する becomes して (irregular)",
    },
    くる: {
      pattern: "くる",
      replacement: "きて",
      description: "くる becomes きて (irregular)",
    },
    いく: {
      pattern: "いく",
      replacement: "いって",
      description: "いく becomes いって (irregular)",
    },
    ある: {
      pattern: "ある",
      replacement: "あって",
      description: "ある becomes あって (irregular)",
    },
  },
  godan: {
    u: {
      pattern: "う",
      replacement: "って",
      description: "For verbs ending in う, replace う with って",
    },
    ku: {
      pattern: "く",
      replacement: "いて",
      description: "For verbs ending in く, replace く with いて",
    },
    gu: {
      pattern: "ぐ",
      replacement: "いで",
      description: "For verbs ending in ぐ, replace ぐ with いで",
    },
    su: {
      pattern: "す",
      replacement: "して",
      description: "For verbs ending in す, replace す with して",
    },
    tsu: {
      pattern: "つ",
      replacement: "って",
      description: "For verbs ending in つ, replace つ with って",
    },
    nu: {
      pattern: "ぬ",
      replacement: "んで",
      description: "For verbs ending in ぬ, replace ぬ with んで",
    },
    bu: {
      pattern: "ぶ",
      replacement: "んで",
      description: "For verbs ending in ぶ, replace ぶ with んで",
    },
    mu: {
      pattern: "む",
      replacement: "んで",
      description: "For verbs ending in む, replace む with んで",
    },
    ru: {
      pattern: "る",
      replacement: "って",
      description: "For godan verbs ending in る, replace る with って",
    },
  },
}

export const verbs: Verb[] = [
  // Ichidan verbs
  {
    kanji: "食べる",
    hiragana: "たべる",
    romaji: "taberu",
    type: "ichidan",
    teForm: "たべて",
    meaning: "to eat",
  },
  {
    kanji: "見る",
    hiragana: "みる",
    romaji: "miru",
    type: "ichidan",
    teForm: "みて",
    meaning: "to see",
  },
  {
    kanji: "寝る",
    hiragana: "ねる",
    romaji: "neru",
    type: "ichidan",
    teForm: "ねて",
    meaning: "to sleep",
  },
  {
    kanji: "起きる",
    hiragana: "おきる",
    romaji: "okiru",
    type: "ichidan",
    teForm: "おきて",
    meaning: "to wake up",
  },
  {
    kanji: "着る",
    hiragana: "きる",
    romaji: "kiru",
    type: "ichidan",
    teForm: "きて",
    meaning: "to wear",
  },
  {
    kanji: "開ける",
    hiragana: "あける",
    romaji: "akeru",
    type: "ichidan",
    teForm: "あけて",
    meaning: "to open",
  },
  {
    kanji: "閉める",
    hiragana: "しめる",
    romaji: "shimeru",
    type: "ichidan",
    teForm: "しめて",
    meaning: "to close",
  },
  {
    kanji: "借りる",
    hiragana: "かりる",
    romaji: "kariru",
    type: "ichidan",
    teForm: "かりて",
    meaning: "to borrow",
  },
  {
    kanji: "貸す",
    hiragana: "かす",
    romaji: "kasu",
    type: "godan",
    teForm: "かして",
    meaning: "to lend",
    endingGroup: "su",
  },
  {
    kanji: "教える",
    hiragana: "おしえる",
    romaji: "oshieru",
    type: "ichidan",
    teForm: "おしえて",
    meaning: "to teach",
  },
  {
    kanji: "覚える",
    hiragana: "おぼえる",
    romaji: "oboeru",
    type: "ichidan",
    teForm: "おぼえて",
    meaning: "to remember",
  },
  {
    kanji: "忘れる",
    hiragana: "わすれる",
    romaji: "wasureru",
    type: "ichidan",
    teForm: "わすれて",
    meaning: "to forget",
  },
  {
    kanji: "疲れる",
    hiragana: "つかれる",
    romaji: "tsukareru",
    type: "ichidan",
    teForm: "つかれて",
    meaning: "to get tired",
  },
  {
    kanji: "出る",
    hiragana: "でる",
    romaji: "deru",
    type: "ichidan",
    teForm: "でて",
    meaning: "to exit",
  },
  {
    kanji: "入れる",
    hiragana: "いれる",
    romaji: "ireru",
    type: "ichidan",
    teForm: "いれて",
    meaning: "to put in",
  },
  {
    kanji: "捨てる",
    hiragana: "すてる",
    romaji: "suteru",
    type: "ichidan",
    teForm: "すてて",
    meaning: "to throw away",
  },
  {
    kanji: "逃げる",
    hiragana: "にげる",
    romaji: "nigeru",
    type: "ichidan",
    teForm: "にげて",
    meaning: "to escape",
  },
  {
    kanji: "助ける",
    hiragana: "たすける",
    romaji: "tasukeru",
    type: "ichidan",
    teForm: "たすけて",
    meaning: "to help",
  },
  {
    kanji: "信じる",
    hiragana: "しんじる",
    romaji: "shinjiru",
    type: "ichidan",
    teForm: "しんじて",
    meaning: "to believe",
  },
  {
    kanji: "生きる",
    hiragana: "いきる",
    romaji: "ikiru",
    type: "ichidan",
    teForm: "いきて",
    meaning: "to live",
  },

  // Godan verbs - む (mu) ending
  {
    kanji: "飲む",
    hiragana: "のむ",
    romaji: "nomu",
    type: "godan",
    teForm: "のんで",
    meaning: "to drink",
    endingGroup: "mu",
  },
  {
    kanji: "読む",
    hiragana: "よむ",
    romaji: "yomu",
    type: "godan",
    teForm: "よんで",
    meaning: "to read",
    endingGroup: "mu",
  },
  {
    kanji: "住む",
    hiragana: "すむ",
    romaji: "sumu",
    type: "godan",
    teForm: "すんで",
    meaning: "to live/reside",
    endingGroup: "mu",
  },
  {
    kanji: "休む",
    hiragana: "やすむ",
    romaji: "yasumu",
    type: "godan",
    teForm: "やすんで",
    meaning: "to rest",
    endingGroup: "mu",
  },
  {
    kanji: "進む",
    hiragana: "すすむ",
    romaji: "susumu",
    type: "godan",
    teForm: "すすんで",
    meaning: "to advance",
    endingGroup: "mu",
  },

  // Godan verbs - く (ku) ending
  {
    kanji: "書く",
    hiragana: "かく",
    romaji: "kaku",
    type: "godan",
    teForm: "かいて",
    meaning: "to write",
    endingGroup: "ku",
  },
  {
    kanji: "歩く",
    hiragana: "あるく",
    romaji: "aruku",
    type: "godan",
    teForm: "あるいて",
    meaning: "to walk",
    endingGroup: "ku",
  },
  {
    kanji: "働く",
    hiragana: "はたらく",
    romaji: "hataraku",
    type: "godan",
    teForm: "はたらいて",
    meaning: "to work",
    endingGroup: "ku",
  },
  {
    kanji: "聞く",
    hiragana: "きく",
    romaji: "kiku",
    type: "godan",
    teForm: "きいて",
    meaning: "to listen/ask",
    endingGroup: "ku",
  },
  {
    kanji: "置く",
    hiragana: "おく",
    romaji: "oku",
    type: "godan",
    teForm: "おいて",
    meaning: "to put/place",
    endingGroup: "ku",
  },
  {
    kanji: "泣く",
    hiragana: "なく",
    romaji: "naku",
    type: "godan",
    teForm: "ないて",
    meaning: "to cry",
    endingGroup: "ku",
  },
  {
    kanji: "焼く",
    hiragana: "やく",
    romaji: "yaku",
    type: "godan",
    teForm: "やいて",
    meaning: "to bake/grill",
    endingGroup: "ku",
  },

  // Godan verbs - ぐ (gu) ending
  {
    kanji: "泳ぐ",
    hiragana: "およぐ",
    romaji: "oyogu",
    type: "godan",
    teForm: "およいで",
    meaning: "to swim",
    endingGroup: "gu",
  },
  {
    kanji: "急ぐ",
    hiragana: "いそぐ",
    romaji: "isogu",
    type: "godan",
    teForm: "いそいで",
    meaning: "to hurry",
    endingGroup: "gu",
  },
  {
    kanji: "脱ぐ",
    hiragana: "ぬぐ",
    romaji: "nugu",
    type: "godan",
    teForm: "ぬいで",
    meaning: "to take off (clothes)",
    endingGroup: "gu",
  },

  // Godan verbs - す (su) ending
  {
    kanji: "話す",
    hiragana: "はなす",
    romaji: "hanasu",
    type: "godan",
    teForm: "はなして",
    meaning: "to speak",
    endingGroup: "su",
  },
  {
    kanji: "出す",
    hiragana: "だす",
    romaji: "dasu",
    type: "godan",
    teForm: "だして",
    meaning: "to take out",
    endingGroup: "su",
  },
  {
    kanji: "消す",
    hiragana: "けす",
    romaji: "kesu",
    type: "godan",
    teForm: "けして",
    meaning: "to erase/turn off",
    endingGroup: "su",
  },
  {
    kanji: "押す",
    hiragana: "おす",
    romaji: "osu",
    type: "godan",
    teForm: "おして",
    meaning: "to push",
    endingGroup: "su",
  },
  {
    kanji: "直す",
    hiragana: "なおす",
    romaji: "naosu",
    type: "godan",
    teForm: "なおして",
    meaning: "to fix",
    endingGroup: "su",
  },
  {
    kanji: "探す",
    hiragana: "さがす",
    romaji: "sagasu",
    type: "godan",
    teForm: "さがして",
    meaning: "to search for",
    endingGroup: "su",
  },

  // Godan verbs - つ (tsu) ending
  {
    kanji: "立つ",
    hiragana: "たつ",
    romaji: "tatsu",
    type: "godan",
    teForm: "たって",
    meaning: "to stand",
    endingGroup: "tsu",
  },
  {
    kanji: "待つ",
    hiragana: "まつ",
    romaji: "matsu",
    type: "godan",
    teForm: "まって",
    meaning: "to wait",
    endingGroup: "tsu",
  },
  {
    kanji: "持つ",
    hiragana: "もつ",
    romaji: "motsu",
    type: "godan",
    teForm: "もって",
    meaning: "to hold",
    endingGroup: "tsu",
  },
  {
    kanji: "打つ",
    hiragana: "うつ",
    romaji: "utsu",
    type: "godan",
    teForm: "うって",
    meaning: "to hit/type",
    endingGroup: "tsu",
  },

  // Godan verbs - ぬ (nu) ending
  {
    kanji: "死ぬ",
    hiragana: "しぬ",
    romaji: "shinu",
    type: "godan",
    teForm: "しんで",
    meaning: "to die",
    endingGroup: "nu",
  },

  // Godan verbs - ぶ (bu) ending
  {
    kanji: "遊ぶ",
    hiragana: "あそぶ",
    romaji: "asobu",
    type: "godan",
    teForm: "あそんで",
    meaning: "to play",
    endingGroup: "bu",
  },
  {
    kanji: "運ぶ",
    hiragana: "はこぶ",
    romaji: "hakobu",
    type: "godan",
    teForm: "はこんで",
    meaning: "to carry",
    endingGroup: "bu",
  },
  {
    kanji: "呼ぶ",
    hiragana: "よぶ",
    romaji: "yobu",
    type: "godan",
    teForm: "よんで",
    meaning: "to call",
    endingGroup: "bu",
  },
  {
    kanji: "学ぶ",
    hiragana: "まなぶ",
    romaji: "manabu",
    type: "godan",
    teForm: "まなんで",
    meaning: "to learn",
    endingGroup: "bu",
  },

  // Godan verbs - う (u) ending
  {
    kanji: "買う",
    hiragana: "かう",
    romaji: "kau",
    type: "godan",
    teForm: "かって",
    meaning: "to buy",
    endingGroup: "u",
  },
  {
    kanji: "歌う",
    hiragana: "うたう",
    romaji: "utau",
    type: "godan",
    teForm: "うたって",
    meaning: "to sing",
    endingGroup: "u",
  },
  {
    kanji: "使う",
    hiragana: "つかう",
    romaji: "tsukau",
    type: "godan",
    teForm: "つかって",
    meaning: "to use",
    endingGroup: "u",
  },
  {
    kanji: "洗う",
    hiragana: "あらう",
    romaji: "arau",
    type: "godan",
    teForm: "あらって",
    meaning: "to wash",
    endingGroup: "u",
  },
  {
    kanji: "笑う",
    hiragana: "わらう",
    romaji: "warau",
    type: "godan",
    teForm: "わらって",
    meaning: "to laugh",
    endingGroup: "u",
  },
  {
    kanji: "踊る",
    hiragana: "おどる",
    romaji: "odoru",
    type: "godan",
    teForm: "おどって",
    meaning: "to dance",
    endingGroup: "ru",
  },

  // Godan verbs - る (ru) ending
  {
    kanji: "作る",
    hiragana: "つくる",
    romaji: "tsukuru",
    type: "godan",
    teForm: "つくって",
    meaning: "to make",
    endingGroup: "ru",
  },
  {
    kanji: "帰る",
    hiragana: "かえる",
    romaji: "kaeru",
    type: "godan",
    teForm: "かえって",
    meaning: "to return home",
    endingGroup: "ru",
  },
  {
    kanji: "座る",
    hiragana: "すわる",
    romaji: "suwaru",
    type: "godan",
    teForm: "すわって",
    meaning: "to sit",
    endingGroup: "ru",
  },
  {
    kanji: "入る",
    hiragana: "はいる",
    romaji: "hairu",
    type: "godan",
    teForm: "はいって",
    meaning: "to enter",
    endingGroup: "ru",
  },
  {
    kanji: "取る",
    hiragana: "とる",
    romaji: "toru",
    type: "godan",
    teForm: "とって",
    meaning: "to take",
    endingGroup: "ru",
  },
  {
    kanji: "撮る",
    hiragana: "とる",
    romaji: "toru",
    type: "godan",
    teForm: "とって",
    meaning: "to take (photo)",
    endingGroup: "ru",
  },
  {
    kanji: "切る",
    hiragana: "きる",
    romaji: "kiru",
    type: "godan",
    teForm: "きって",
    meaning: "to cut",
    endingGroup: "ru",
  },
  {
    kanji: "売る",
    hiragana: "うる",
    romaji: "uru",
    type: "godan",
    teForm: "うって",
    meaning: "to sell",
    endingGroup: "ru",
  },
  {
    kanji: "知る",
    hiragana: "しる",
    romaji: "shiru",
    type: "godan",
    teForm: "しって",
    meaning: "to know",
    endingGroup: "ru",
  },
  {
    kanji: "走る",
    hiragana: "はしる",
    romaji: "hashiru",
    type: "godan",
    teForm: "はしって",
    meaning: "to run",
    endingGroup: "ru",
  },

  // Irregular verbs
  {
    kanji: "する",
    hiragana: "する",
    romaji: "suru",
    type: "irregular",
    teForm: "して",
    meaning: "to do",
  },
  {
    kanji: "来る",
    hiragana: "くる",
    romaji: "kuru",
    type: "irregular",
    teForm: "きて",
    meaning: "to come",
  },
  {
    kanji: "行く",
    hiragana: "いく",
    romaji: "iku",
    type: "irregular",
    teForm: "いって",
    meaning: "to go",
  },
  {
    kanji: "ある",
    hiragana: "ある",
    romaji: "aru",
    type: "irregular",
    teForm: "あって",
    meaning: "to exist (inanimate)",
  },

  // Compound verbs with する
  {
    kanji: "勉強する",
    hiragana: "べんきょうする",
    romaji: "benkyou suru",
    type: "irregular",
    teForm: "べんきょうして",
    meaning: "to study",
  },
  {
    kanji: "料理する",
    hiragana: "りょうりする",
    romaji: "ryouri suru",
    type: "irregular",
    teForm: "りょうりして",
    meaning: "to cook",
  },
  {
    kanji: "掃除する",
    hiragana: "そうじする",
    romaji: "souji suru",
    type: "irregular",
    teForm: "そうじして",
    meaning: "to clean",
  },
  {
    kanji: "洗濯する",
    hiragana: "せんたくする",
    romaji: "sentaku suru",
    type: "irregular",
    teForm: "せんたくして",
    meaning: "to do laundry",
  },
  {
    kanji: "買い物する",
    hiragana: "かいものする",
    romaji: "kaimono suru",
    type: "irregular",
    teForm: "かいものして",
    meaning: "to shop",
  },
  {
    kanji: "散歩する",
    hiragana: "さんぽする",
    romaji: "sanpo suru",
    type: "irregular",
    teForm: "さんぽして",
    meaning: "to take a walk",
  },
  {
    kanji: "運転する",
    hiragana: "うんてんする",
    romaji: "unten suru",
    type: "irregular",
    teForm: "うんてんして",
    meaning: "to drive",
  },
  {
    kanji: "電話する",
    hiragana: "でんわする",
    romaji: "denwa suru",
    type: "irregular",
    teForm: "でんわして",
    meaning: "to make a phone call",
  },
  {
    kanji: "旅行する",
    hiragana: "りょこうする",
    romaji: "ryokou suru",
    type: "irregular",
    teForm: "りょこうして",
    meaning: "to travel",
  },
  {
    kanji: "結婚する",
    hiragana: "けっこんする",
    romaji: "kekkon suru",
    type: "irregular",
    teForm: "けっこんして",
    meaning: "to get married",
  },

  // Additional common verbs
  {
    kanji: "いる",
    hiragana: "いる",
    romaji: "iru",
    type: "ichidan",
    teForm: "いて",
    meaning: "to exist (animate)",
  },
  {
    kanji: "できる",
    hiragana: "できる",
    romaji: "dekiru",
    type: "ichidan",
    teForm: "できて",
    meaning: "to be able to",
  },
  {
    kanji: "始める",
    hiragana: "はじめる",
    romaji: "hajimeru",
    type: "ichidan",
    teForm: "はじめて",
    meaning: "to start",
  },
  {
    kanji: "終わる",
    hiragana: "おわる",
    romaji: "owaru",
    type: "godan",
    teForm: "おわって",
    meaning: "to end",
    endingGroup: "ru",
  },
  {
    kanji: "分かる",
    hiragana: "わかる",
    romaji: "wakaru",
    type: "godan",
    teForm: "わかって",
    meaning: "to understand",
    endingGroup: "ru",
  },
  {
    kanji: "会う",
    hiragana: "あう",
    romaji: "au",
    type: "godan",
    teForm: "あって",
    meaning: "to meet",
    endingGroup: "u",
  },
]
