import type { TeFormRules, Verb } from "./types"

export const teFormRules: TeFormRules = {
  ichidan: {
    pattern: "る",
    replacement: "て",
    description: "For ichidan verbs, simply replace る with て",
  },
  irregular: {
    する: {
      pattern: "する",
      replacement: "して",
      description: "する becomes して (irregular)",
    },
    くる: {
      pattern: "くる",
      replacement: "きて",
      description: "くる becomes きて (irregular)",
    },
    いく: {
      pattern: "いく",
      replacement: "いって",
      description: "いく becomes いって (irregular)",
    },
    ある: {
      pattern: "ある",
      replacement: "あって",
      description: "ある becomes あって (irregular)",
    },
  },
  godan: {
    u: {
      pattern: "う",
      replacement: "って",
      description: "For verbs ending in う, replace う with って",
    },
    ku: {
      pattern: "く",
      replacement: "いて",
      description: "For verbs ending in く, replace く with いて",
    },
    gu: {
      pattern: "ぐ",
      replacement: "いで",
      description: "For verbs ending in ぐ, replace ぐ with いで",
    },
    su: {
      pattern: "す",
      replacement: "して",
      description: "For verbs ending in す, replace す with して",
    },
    tsu: {
      pattern: "つ",
      replacement: "って",
      description: "For verbs ending in つ, replace つ with って",
    },
    nu: {
      pattern: "ぬ",
      replacement: "んで",
      description: "For verbs ending in ぬ, replace ぬ with んで",
    },
    bu: {
      pattern: "ぶ",
      replacement: "んで",
      description: "For verbs ending in ぶ, replace ぶ with んで",
    },
    mu: {
      pattern: "む",
      replacement: "んで",
      description: "For verbs ending in む, replace む with んで",
    },
    ru: {
      pattern: "る",
      replacement: "って",
      description: "For godan verbs ending in る, replace る with って",
    },
  },
}

export const verbs: Verb[] = [
  // Ichidan verbs
  {
    kanji: "食べる",
    hiragana: "たべる",
    romaji: "taberu",
    type: "ichidan",
    teForm: "たべて",
    meaning: "to eat",
  },
  {
    kanji: "見る",
    hiragana: "みる",
    romaji: "miru",
    type: "ichidan",
    teForm: "みて",
    meaning: "to see",
  },
  {
    kanji: "寝る",
    hiragana: "ねる",
    romaji: "neru",
    type: "ichidan",
    teForm: "ねて",
    meaning: "to sleep",
  },
  {
    kanji: "起きる",
    hiragana: "おきる",
    romaji: "okiru",
    type: "ichidan",
    teForm: "おきて",
    meaning: "to wake up",
  },
  {
    kanji: "着る",
    hiragana: "きる",
    romaji: "kiru",
    type: "ichidan",
    teForm: "きて",
    meaning: "to wear",
  },

  // Godan verbs
  {
    kanji: "飲む",
    hiragana: "のむ",
    romaji: "nomu",
    type: "godan",
    teForm: "のんで",
    meaning: "to drink",
    endingGroup: "mu",
  },
  {
    kanji: "読む",
    hiragana: "よむ",
    romaji: "yomu",
    type: "godan",
    teForm: "よんで",
    meaning: "to read",
    endingGroup: "mu",
  },
  {
    kanji: "書く",
    hiragana: "かく",
    romaji: "kaku",
    type: "godan",
    teForm: "かいて",
    meaning: "to write",
    endingGroup: "ku",
  },
  {
    kanji: "泳ぐ",
    hiragana: "およぐ",
    romaji: "oyogu",
    type: "godan",
    teForm: "およいで",
    meaning: "to swim",
    endingGroup: "gu",
  },
  {
    kanji: "話す",
    hiragana: "はなす",
    romaji: "hanasu",
    type: "godan",
    teForm: "はなして",
    meaning: "to speak",
    endingGroup: "su",
  },
  {
    kanji: "立つ",
    hiragana: "たつ",
    romaji: "tatsu",
    type: "godan",
    teForm: "たって",
    meaning: "to stand",
    endingGroup: "tsu",
  },
  {
    kanji: "死ぬ",
    hiragana: "しぬ",
    romaji: "shinu",
    type: "godan",
    teForm: "しんで",
    meaning: "to die",
    endingGroup: "nu",
  },
  {
    kanji: "遊ぶ",
    hiragana: "あそぶ",
    romaji: "asobu",
    type: "godan",
    teForm: "あそんで",
    meaning: "to play",
    endingGroup: "bu",
  },
  {
    kanji: "買う",
    hiragana: "かう",
    romaji: "kau",
    type: "godan",
    teForm: "かって",
    meaning: "to buy",
    endingGroup: "u",
  },
  {
    kanji: "作る",
    hiragana: "つくる",
    romaji: "tsukuru",
    type: "godan",
    teForm: "つくって",
    meaning: "to make",
    endingGroup: "ru",
  },

  // Irregular verbs
  {
    kanji: "する",
    hiragana: "する",
    romaji: "suru",
    type: "irregular",
    teForm: "して",
    meaning: "to do",
  },
  {
    kanji: "来る",
    hiragana: "くる",
    romaji: "kuru",
    type: "irregular",
    teForm: "きて",
    meaning: "to come",
  },
  {
    kanji: "行く",
    hiragana: "いく",
    romaji: "iku",
    type: "irregular",
    teForm: "いって",
    meaning: "to go",
  },
  {
    kanji: "ある",
    hiragana: "ある",
    romaji: "aru",
    type: "irregular",
    teForm: "あって",
    meaning: "to exist (inanimate)",
  },
]
