export type VerbType = 'ichidan' | 'godan' | 'irregular';

export interface Verb {
  kanji: string;
  hiragana: string;
  romaji: string;
  type: VerbType;
  meaning: string;
  endingGroup?: string; // For godan verbs, indicates the ending group (e.g., 'u', 'ku', 'su', etc.)
}

export const verbs: Verb[] = [
  // Ichidan verbs
  {
    kanji: '食べる',
    hiragana: 'たべる',
    romaji: 'taberu',
    type: 'ichidan',
    meaning: 'to eat',
  },
  {
    kanji: '見る',
    hiragana: 'みる',
    romaji: 'miru',
    type: 'ichidan',
    meaning: 'to see',
  },
  {
    kanji: '寝る',
    hiragana: 'ねる',
    romaji: 'neru',
    type: 'ichidan',
    meaning: 'to sleep',
  },
  {
    kanji: '起きる',
    hiragana: 'おきる',
    romaji: 'okiru',
    type: 'ichidan',
    meaning: 'to wake up',
  },
  {
    kanji: '着る',
    hiragana: 'きる',
    romaji: 'kiru',
    type: 'ichidan',
    meaning: 'to wear',
  },
  {
    kanji: '開ける',
    hiragana: 'あける',
    romaji: 'akeru',
    type: 'ichidan',
    meaning: 'to open',
  },
  {
    kanji: '閉める',
    hiragana: 'しめる',
    romaji: 'shimeru',
    type: 'ichidan',
    meaning: 'to close',
  },
  {
    kanji: '借りる',
    hiragana: 'かりる',
    romaji: 'kariru',
    type: 'ichidan',
    meaning: 'to borrow',
  },
  {
    kanji: '貸す',
    hiragana: 'かす',
    romaji: 'kasu',
    type: 'godan',
    meaning: 'to lend',
    endingGroup: 'su',
  },
  {
    kanji: '教える',
    hiragana: 'おしえる',
    romaji: 'oshieru',
    type: 'ichidan',
    meaning: 'to teach',
  },
  {
    kanji: '覚える',
    hiragana: 'おぼえる',
    romaji: 'oboeru',
    type: 'ichidan',
    meaning: 'to remember',
  },
  {
    kanji: '忘れる',
    hiragana: 'わすれる',
    romaji: 'wasureru',
    type: 'ichidan',
    meaning: 'to forget',
  },
  {
    kanji: '疲れる',
    hiragana: 'つかれる',
    romaji: 'tsukareru',
    type: 'ichidan',
    meaning: 'to get tired',
  },
  {
    kanji: '出る',
    hiragana: 'でる',
    romaji: 'deru',
    type: 'ichidan',
    meaning: 'to exit',
  },
  {
    kanji: '入れる',
    hiragana: 'いれる',
    romaji: 'ireru',
    type: 'ichidan',
    meaning: 'to put in',
  },
  {
    kanji: '捨てる',
    hiragana: 'すてる',
    romaji: 'suteru',
    type: 'ichidan',
    meaning: 'to throw away',
  },
  {
    kanji: '逃げる',
    hiragana: 'にげる',
    romaji: 'nigeru',
    type: 'ichidan',
    meaning: 'to escape',
  },
  {
    kanji: '助ける',
    hiragana: 'たすける',
    romaji: 'tasukeru',
    type: 'ichidan',
    meaning: 'to help',
  },
  {
    kanji: '信じる',
    hiragana: 'しんじる',
    romaji: 'shinjiru',
    type: 'ichidan',
    meaning: 'to believe',
  },
  {
    kanji: '生きる',
    hiragana: 'いきる',
    romaji: 'ikiru',
    type: 'ichidan',
    meaning: 'to live',
  },

  // Godan verbs - む (mu) ending
  {
    kanji: '飲む',
    hiragana: 'のむ',
    romaji: 'nomu',
    type: 'godan',
    meaning: 'to drink',
    endingGroup: 'mu',
  },
  {
    kanji: '読む',
    hiragana: 'よむ',
    romaji: 'yomu',
    type: 'godan',
    meaning: 'to read',
    endingGroup: 'mu',
  },
  {
    kanji: '住む',
    hiragana: 'すむ',
    romaji: 'sumu',
    type: 'godan',
    meaning: 'to live/reside',
    endingGroup: 'mu',
  },
  {
    kanji: '休む',
    hiragana: 'やすむ',
    romaji: 'yasumu',
    type: 'godan',
    meaning: 'to rest',
    endingGroup: 'mu',
  },
  {
    kanji: '進む',
    hiragana: 'すすむ',
    romaji: 'susumu',
    type: 'godan',
    meaning: 'to advance',
    endingGroup: 'mu',
  },

  // Godan verbs - く (ku) ending
  {
    kanji: '書く',
    hiragana: 'かく',
    romaji: 'kaku',
    type: 'godan',
    meaning: 'to write',
    endingGroup: 'ku',
  },
  {
    kanji: '歩く',
    hiragana: 'あるく',
    romaji: 'aruku',
    type: 'godan',
    meaning: 'to walk',
    endingGroup: 'ku',
  },
  {
    kanji: '働く',
    hiragana: 'はたらく',
    romaji: 'hataraku',
    type: 'godan',
    meaning: 'to work',
    endingGroup: 'ku',
  },
  {
    kanji: '聞く',
    hiragana: 'きく',
    romaji: 'kiku',
    type: 'godan',
    meaning: 'to listen/ask',
    endingGroup: 'ku',
  },
  {
    kanji: '置く',
    hiragana: 'おく',
    romaji: 'oku',
    type: 'godan',
    meaning: 'to put/place',
    endingGroup: 'ku',
  },
  {
    kanji: '泣く',
    hiragana: 'なく',
    romaji: 'naku',
    type: 'godan',
    meaning: 'to cry',
    endingGroup: 'ku',
  },
  {
    kanji: '焼く',
    hiragana: 'やく',
    romaji: 'yaku',
    type: 'godan',
    meaning: 'to bake/grill',
    endingGroup: 'ku',
  },

  // Godan verbs - ぐ (gu) ending
  {
    kanji: '泳ぐ',
    hiragana: 'およぐ',
    romaji: 'oyogu',
    type: 'godan',
    meaning: 'to swim',
    endingGroup: 'gu',
  },
  {
    kanji: '急ぐ',
    hiragana: 'いそぐ',
    romaji: 'isogu',
    type: 'godan',
    meaning: 'to hurry',
    endingGroup: 'gu',
  },
  {
    kanji: '脱ぐ',
    hiragana: 'ぬぐ',
    romaji: 'nugu',
    type: 'godan',
    meaning: 'to take off (clothes)',
    endingGroup: 'gu',
  },

  // Godan verbs - す (su) ending
  {
    kanji: '話す',
    hiragana: 'はなす',
    romaji: 'hanasu',
    type: 'godan',
    meaning: 'to speak',
    endingGroup: 'su',
  },
  {
    kanji: '出す',
    hiragana: 'だす',
    romaji: 'dasu',
    type: 'godan',
    meaning: 'to take out',
    endingGroup: 'su',
  },
  {
    kanji: '消す',
    hiragana: 'けす',
    romaji: 'kesu',
    type: 'godan',
    meaning: 'to erase/turn off',
    endingGroup: 'su',
  },
  {
    kanji: '押す',
    hiragana: 'おす',
    romaji: 'osu',
    type: 'godan',
    meaning: 'to push',
    endingGroup: 'su',
  },
  {
    kanji: '直す',
    hiragana: 'なおす',
    romaji: 'naosu',
    type: 'godan',
    meaning: 'to fix',
    endingGroup: 'su',
  },
  {
    kanji: '探す',
    hiragana: 'さがす',
    romaji: 'sagasu',
    type: 'godan',
    meaning: 'to search for',
    endingGroup: 'su',
  },

  // Godan verbs - つ (tsu) ending
  {
    kanji: '立つ',
    hiragana: 'たつ',
    romaji: 'tatsu',
    type: 'godan',
    meaning: 'to stand',
    endingGroup: 'tsu',
  },
  {
    kanji: '待つ',
    hiragana: 'まつ',
    romaji: 'matsu',
    type: 'godan',
    meaning: 'to wait',
    endingGroup: 'tsu',
  },
  {
    kanji: '持つ',
    hiragana: 'もつ',
    romaji: 'motsu',
    type: 'godan',
    meaning: 'to hold',
    endingGroup: 'tsu',
  },
  {
    kanji: '打つ',
    hiragana: 'うつ',
    romaji: 'utsu',
    type: 'godan',
    meaning: 'to hit/type',
    endingGroup: 'tsu',
  },

  // Godan verbs - ぬ (nu) ending
  {
    kanji: '死ぬ',
    hiragana: 'しぬ',
    romaji: 'shinu',
    type: 'godan',
    meaning: 'to die',
    endingGroup: 'nu',
  },

  // Godan verbs - ぶ (bu) ending
  {
    kanji: '遊ぶ',
    hiragana: 'あそぶ',
    romaji: 'asobu',
    type: 'godan',
    meaning: 'to play',
    endingGroup: 'bu',
  },
  {
    kanji: '運ぶ',
    hiragana: 'はこぶ',
    romaji: 'hakobu',
    type: 'godan',
    meaning: 'to carry',
    endingGroup: 'bu',
  },
  {
    kanji: '呼ぶ',
    hiragana: 'よぶ',
    romaji: 'yobu',
    type: 'godan',
    meaning: 'to call',
    endingGroup: 'bu',
  },
  {
    kanji: '学ぶ',
    hiragana: 'まなぶ',
    romaji: 'manabu',
    type: 'godan',
    meaning: 'to learn',
    endingGroup: 'bu',
  },

  // Godan verbs - う (u) ending
  {
    kanji: '買う',
    hiragana: 'かう',
    romaji: 'kau',
    type: 'godan',
    meaning: 'to buy',
    endingGroup: 'u',
  },
  {
    kanji: '歌う',
    hiragana: 'うたう',
    romaji: 'utau',
    type: 'godan',
    meaning: 'to sing',
    endingGroup: 'u',
  },
  {
    kanji: '使う',
    hiragana: 'つかう',
    romaji: 'tsukau',
    type: 'godan',
    meaning: 'to use',
    endingGroup: 'u',
  },
  {
    kanji: '洗う',
    hiragana: 'あらう',
    romaji: 'arau',
    type: 'godan',
    meaning: 'to wash',
    endingGroup: 'u',
  },
  {
    kanji: '笑う',
    hiragana: 'わらう',
    romaji: 'warau',
    type: 'godan',
    meaning: 'to laugh',
    endingGroup: 'u',
  },
  {
    kanji: '踊る',
    hiragana: 'おどる',
    romaji: 'odoru',
    type: 'godan',
    meaning: 'to dance',
    endingGroup: 'ru',
  },

  // Godan verbs - る (ru) ending
  {
    kanji: '作る',
    hiragana: 'つくる',
    romaji: 'tsukuru',
    type: 'godan',
    meaning: 'to make',
    endingGroup: 'ru',
  },
  {
    kanji: '帰る',
    hiragana: 'かえる',
    romaji: 'kaeru',
    type: 'godan',
    meaning: 'to return home',
    endingGroup: 'ru',
  },
  {
    kanji: '座る',
    hiragana: 'すわる',
    romaji: 'suwaru',
    type: 'godan',
    meaning: 'to sit',
    endingGroup: 'ru',
  },
  {
    kanji: '入る',
    hiragana: 'はいる',
    romaji: 'hairu',
    type: 'godan',
    meaning: 'to enter',
    endingGroup: 'ru',
  },
  {
    kanji: '取る',
    hiragana: 'とる',
    romaji: 'toru',
    type: 'godan',
    meaning: 'to take',
    endingGroup: 'ru',
  },
  {
    kanji: '撮る',
    hiragana: 'とる',
    romaji: 'toru',
    type: 'godan',
    meaning: 'to take (photo)',
    endingGroup: 'ru',
  },
  {
    kanji: '切る',
    hiragana: 'きる',
    romaji: 'kiru',
    type: 'godan',
    meaning: 'to cut',
    endingGroup: 'ru',
  },
  {
    kanji: '売る',
    hiragana: 'うる',
    romaji: 'uru',
    type: 'godan',
    meaning: 'to sell',
    endingGroup: 'ru',
  },
  {
    kanji: '知る',
    hiragana: 'しる',
    romaji: 'shiru',
    type: 'godan',
    meaning: 'to know',
    endingGroup: 'ru',
  },
  {
    kanji: '走る',
    hiragana: 'はしる',
    romaji: 'hashiru',
    type: 'godan',
    meaning: 'to run',
    endingGroup: 'ru',
  },

  // Irregular verbs
  {
    kanji: 'する',
    hiragana: 'する',
    romaji: 'suru',
    type: 'irregular',
    meaning: 'to do',
  },
  {
    kanji: '来る',
    hiragana: 'くる',
    romaji: 'kuru',
    type: 'irregular',
    meaning: 'to come',
  },
  {
    kanji: '行く',
    hiragana: 'いく',
    romaji: 'iku',
    type: 'irregular',
    meaning: 'to go',
  },
  {
    kanji: 'ある',
    hiragana: 'ある',
    romaji: 'aru',
    type: 'irregular',
    meaning: 'to exist (inanimate)',
  },

  // Compound verbs with する
  {
    kanji: '勉強する',
    hiragana: 'べんきょうする',
    romaji: 'benkyou suru',
    type: 'irregular',
    meaning: 'to study',
  },
  {
    kanji: '料理する',
    hiragana: 'りょうりする',
    romaji: 'ryouri suru',
    type: 'irregular',
    meaning: 'to cook',
  },
  {
    kanji: '掃除する',
    hiragana: 'そうじする',
    romaji: 'souji suru',
    type: 'irregular',
    meaning: 'to clean',
  },
  {
    kanji: '洗濯する',
    hiragana: 'せんたくする',
    romaji: 'sentaku suru',
    type: 'irregular',
    meaning: 'to do laundry',
  },
  {
    kanji: '買い物する',
    hiragana: 'かいものする',
    romaji: 'kaimono suru',
    type: 'irregular',
    meaning: 'to shop',
  },
  {
    kanji: '散歩する',
    hiragana: 'さんぽする',
    romaji: 'sanpo suru',
    type: 'irregular',
    meaning: 'to take a walk',
  },
  {
    kanji: '運転する',
    hiragana: 'うんてんする',
    romaji: 'unten suru',
    type: 'irregular',
    meaning: 'to drive',
  },
  {
    kanji: '電話する',
    hiragana: 'でんわする',
    romaji: 'denwa suru',
    type: 'irregular',
    meaning: 'to make a phone call',
  },
  {
    kanji: '旅行する',
    hiragana: 'りょこうする',
    romaji: 'ryokou suru',
    type: 'irregular',
    meaning: 'to travel',
  },
  {
    kanji: '結婚する',
    hiragana: 'けっこんする',
    romaji: 'kekkon suru',
    type: 'irregular',
    meaning: 'to get married',
  },

  // Additional common verbs
  {
    kanji: 'いる',
    hiragana: 'いる',
    romaji: 'iru',
    type: 'ichidan',
    meaning: 'to exist (animate)',
  },
  {
    kanji: 'できる',
    hiragana: 'できる',
    romaji: 'dekiru',
    type: 'ichidan',
    meaning: 'to be able to',
  },
  {
    kanji: '始める',
    hiragana: 'はじめる',
    romaji: 'hajimeru',
    type: 'ichidan',
    meaning: 'to start',
  },
  {
    kanji: '終わる',
    hiragana: 'おわる',
    romaji: 'owaru',
    type: 'godan',
    meaning: 'to end',
    endingGroup: 'ru',
  },
  {
    kanji: '分かる',
    hiragana: 'わかる',
    romaji: 'wakaru',
    type: 'godan',
    meaning: 'to understand',
    endingGroup: 'ru',
  },
  {
    kanji: '会う',
    hiragana: 'あう',
    romaji: 'au',
    type: 'godan',
    meaning: 'to meet',
    endingGroup: 'u',
  },
];

export function randomVerbs(): Verb[] {
  const shuffled = [...verbs].sort(() => 0.5 - Math.random());
  return shuffled;
}
